# Generated by Django 2.1.3 on 2019-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ('provincia', 'nombre'), 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ('region', 'nombre'), 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('nombre', 'id_region'), 'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
    ]
