# Generated by Django 2.1.3 on 2019-03-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0003_auto_20190307_1442'),
        ('Profesor', '0002_auto_20190118_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(choices=[('Tesis', 'Tesis'), ('Investigacion', 'Investigacion')], max_length=20)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor')),
            ],
        ),
    ]
