# Generated by Django 2.1.3 on 2019-03-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0003_auto_20190307_1442'),
        ('Profesor', '0002_auto_20190118_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('sigla', models.CharField(max_length=10)),
                ('creditos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Optativo', 'Optativo'), ('Obligatorio', 'Obligatorio')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_cursado', models.CharField(blank=True, max_length=4)),
                ('semestre', models.CharField(blank=True, max_length=2)),
                ('paralelo', models.IntegerField()),
                ('aprobados', models.CharField(blank=True, max_length=300, null=True)),
                ('rechazados', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('inscritos', models.CharField(blank=True, max_length=500, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_alumnos',
            fields=[
                ('id_lista', models.BigAutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='lista_alumnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Lista_alumnos'),
        ),
        migrations.AddField(
            model_name='detalle_curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor'),
        ),
    ]
