# Generated by Django 2.1.3 on 2019-03-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0006_auto_20190311_1421'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(blank=True, choices=[('1er Semestre', '1er Semestre'), ('2do Semestre', '2do Semestre')], max_length=50, null=True)),
                ('anio_cursado', models.CharField(blank=True, max_length=4)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Retiro', 'Retiro')], max_length=300)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ('anio_cursado', 'estado'),
            },
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ('nombre', 'sigla', 'creditos'), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='detalle_curso',
            options={'ordering': ('anio_cursado', 'semestre', 'curso'), 'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AlterModelOptions(
            name='lista_alumnos',
            options={'ordering': ('id_lista', 'alumno'), 'verbose_name': 'Lista', 'verbose_name_plural': 'Listas'},
        ),
        migrations.AddField(
            model_name='avancecurricular',
            name='curso',
            field=models.ManyToManyField(blank=True, to='Cursos.Cursos'),
        ),
    ]
