# Generated by Django 2.1.3 on 2019-03-07 14:42

import Alumno.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_auto_20190118_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=13, validators=[Alumno.validators.digito_verificador]),
        ),
    ]
