# Generated by Django 2.1.3 on 2019-03-07 18:33

import Alumno.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_auto_20190307_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(validators=[Alumno.validators.validateDateEs]),
        ),
    ]
