# Generated by Django 2.1.3 on 2019-03-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionsede',
            options={'ordering': ('region', 'provincia', 'comuna', 'sede'), 'verbose_name': 'DireccionSede', 'verbose_name_plural': 'DireccionesSede'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ('nombre', 'alumno'), 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
    ]
